allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  core-js: true
  esbuild: set this to true or false
  msgpackr-extract: set this to true or false
  nodemon: true
  prisma: true
  workerd: set this to true or false
